# Generated by Django 5.1.6 on 2025-05-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpetas', '0002_documento_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='descripcion',
        ),
    ]
