# Generated by Django 5.1.6 on 2025-05-23 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpetas', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=100)),
                ('institucion_financiera', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('ruc_ci', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=100)),
                ('clave_web', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='carpetas.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='CXC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('real', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cxcs', to='carpetas.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorteo', models.DateField(blank=True, null=True)),
                ('proceso', models.CharField(max_length=200)),
                ('calificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.CharField(default='Desconocido', max_length=200)),
                ('demandado', models.CharField(default='Desconocido', max_length=200)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('posesion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_cumplimiento', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('hecho', 'Hecho'), ('pendiente', 'Pendiente'), ('faltan_datos', 'Faltan datos')], default='pendiente', max_length=20)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='carpetas.carpeta')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(default='general', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_control', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control_procesos.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobro', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_cobrar', to='carpetas.carpeta')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_cobrar', to='control_procesos.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClavesSistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(blank=True, max_length=200, null=True)),
                ('canton', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clave_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_declaracion', models.DateField(blank=True, null=True)),
                ('declaracion', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_sri', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_super', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_iess', models.CharField(blank=True, max_length=100, null=True)),
                ('perito_judicial', models.CharField(blank=True, max_length=100, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clavesSistemas', to='carpetas.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion_financiera', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('ruc_ci', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_web', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_cajero', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_trush', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_sut', models.CharField(blank=True, max_length=100, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentasEspeciales', to='carpetas.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perito', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=100)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='carpetas.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntasEspeciales', to='carpetas.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('clave', models.CharField(blank=True, max_length=100, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemasEspeciales', to='carpetas.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateField()),
                ('calificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_cumplimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='carpetas.carpeta')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='control_procesos.proceso')),
            ],
        ),
    ]
